### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by shraddha360** [JeffersonReisPro/unity3d-webgl-with-google-speech-recognition#1]
Hi,
Its not working,May be I am doing something wrong.Can you add instructions?

**Comment by JeffersonReisPro** [comment]
This adaptation with voice recognition was a specific experiment for Google Chrome. Probably no longer valid with updates from Unity 3D and Google Chrome.

**Comment by JeffersonReisPro** [comment]
> Hi,
> Its not working,May be I am doing something wrong.Can you add instructions?
